import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class AttendancePdfGenerator {
  static Future<void> generateAndShare({
    required String courseName,
    required String courseCode,
    required List<dynamic> students,
    required String filterType,
    double? customThreshold,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final dateStr = DateFormat('dd MMM yyyy').format(now);
    final fileName = "${courseName.replaceAll(' ', '_')}_$dateStr.pdf";

    // Filter students based on selection
    List<dynamic> filteredStudents = List.from(students);
    if (filterType == 'Below 75%') {
      filteredStudents =
          students.where((s) => (s['attendancePercentage'] ?? 0) < 75).toList();
    } else if (filterType == 'Custom' && customThreshold != null) {
      filteredStudents = students
          .where((s) => (s['attendancePercentage'] ?? 0) < customThreshold)
          .toList();
    }

    // Sort by roll number
    filteredStudents.sort((a, b) {
      final rA = (a['rollNo'] ?? '').toString();
      final rB = (b['rollNo'] ?? '').toString();
      return rA.compareTo(rB);
    });

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(courseName,
                      style: pw.TextStyle(
                          fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 4),
                  pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: [
                      pw.Text('Course Code: $courseCode',
                          style: const pw.TextStyle(fontSize: 14)),
                      pw.Text('Export Date: $dateStr',
                          style: const pw.TextStyle(fontSize: 14)),
                    ],
                  ),
                  pw.Divider(thickness: 2),
                  pw.SizedBox(height: 10),
                  pw.Text('Attendance Report: $filterType',
                      style: pw.TextStyle(
                          fontSize: 16, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 20),
                ],
              ),
            ),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300),
              children: [
                // Header row
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: [
                    _buildCell('SN', isHeader: true),
                    _buildCell('Roll No', isHeader: true),
                    _buildCell('Student Name', isHeader: true),
                    _buildCell('Attended', isHeader: true),
                    _buildCell('Total', isHeader: true),
                    _buildCell('Percentage', isHeader: true),
                  ],
                ),
                // Data rows
                ...filteredStudents.asMap().entries.map((entry) {
                  final index = entry.key;
                  final s = entry.value;
                  final name = s['name'] ?? 'Unknown';
                  final rollNo = (s['rollNo'] ?? s['rollNumber'] ?? 'N/A').toString();
                  final percentage = s['attendancePercentage'] ?? 0;
                  
                  // Calculate sessions
                  final sessions = s['sessions'] as Map<String, dynamic>? ?? {};
                  final total = sessions.length;
                  final attended = sessions.values.where((v) => v == 'present').length;

                  return pw.TableRow(
                    children: [
                      _buildCell((index + 1).toString()),
                      _buildCell(rollNo),
                      _buildCell(name, align: pw.Alignment.centerLeft),
                      _buildCell(attended.toString()),
                      _buildCell(total.toString()),
                      _buildCell('$percentage%'),
                    ],
                  );
                }),
              ],
            ),
            pw.Footer(
              margin: const pw.EdgeInsets.only(top: 20),
              trailing: pw.Text('Generated by IIITNR Attendance System',
                  style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
            ),
          ];
        },
      ),
    );

    // Provide immediate save/print options
    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: fileName,
    );
  }

  static pw.Widget _buildCell(String text,
      {bool isHeader = false, pw.Alignment align = pw.Alignment.center}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Container(
        alignment: align,
        child: pw.Text(
          text,
          style: pw.TextStyle(
            fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
            fontSize: isHeader ? 11 : 10,
          ),
        ),
      ),
    );
  }
}
